---
#############################################
# Check W
#############################################
- hosts: default
  gather_facts: False
  tasks:
    - name: Check W
      command: w
      register: check_w
    - debug: var=check_w.stdout_lines

